sudo: required
services:
    -docker
    
before_install:
    - docker build -t yogeshkarve/docker-react -f Dockerfile.dev .
    
script:
    - docker run yogeshkarve/docker-react npm run test -- --coverage